language: node_js
node_js:
    - "node"
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc -y
  - sudo apt-get install g++ -y
